### ISSUE TITLE
KeyError: 'limit'

### ISSUE THREAD

**Issue by kenorb** [bullsignals/binance-downloader#19]
```
$ kline-binance -i 1m -st 01/01/2016 -e 31/12/2016 -o ETHBTC-2016.csv
Traceback (most recent call last):
  File "/usr/local/bin/kline-binance", line 4, in <module>
    main()
  File "bullsignals/binance-downloader/binance/cli.py", line 38, in main
    if int(kwargs['limit']) > 500 and not (args.start and args.end):
KeyError: 'limit'
```

Can you make the `--limit` set by default?

**Comment by anderson89marques** [comment]
Hi @kenorb,
thanks for your comment.
I will do that faster as possible.

**Comment by anderson89marques** [comment]
Hi @kenorb, 
This issue is now fixed.
